  check50:
    checks:
      hello world:
        - run: ./hello # run hello.c
          stdin: Douglas # insert name into stdin
          stdout: Hello, Douglas! # expect name in stdout
          exit: 0 # expect program to exit with exitcode 0