check50:
  checks:

    Two digits including a zero:
    - run: ./add_digits
      stdin: 1
      stdout: 1
      exit: 0
        
    Four digits:
    - run: ./add_digits
      stdin: 4978
      stdout: 28
      exit: 0
      
    Single digit:
    - run: ./add_digits
      stdin: 1
      stdout: 1
      exit: 0

    Zero:
    - run: ./add_digits
      stdin: 0
      stdout: 0
      exit: 0