  check50:
    checks:
      multiline months greater than 28:
      - run: ./calendar 1 29
      stdout: blah
      exit: 0
      
#      multiline months greater than 28:
#      - run: ./calendar 1 29
#      stdout: |
#        SU MO TU WE TH FR SA
#        1  2  3  4  5  6  7 
#        8  9 10 11 12 13 14 
#        15 16 17 18 19 20 21 
#        22 23 24 25 26 27 28 
#        29 
#      exit: 0