check50:
  checks:
    sunday 29:
      - run: ./calendar 1 29
        stdout: |
          SU MO TU WE TH FR SA
           1  2  3  4  5  6  7 
           8  9 10 11 12 13 14 
          15 16 17 18 19 20 21 
          22 23 24 25 26 27 28 
          29 
        exit: 0
    saturday 28:
      - run: ./calendar 7 28
        stdout: |
          SU MO TU WE TH FR SA
                             1 
           2  3  4  5  6  7  8 
           9 10 11 12 13 14 15 
          16 17 18 19 20 21 22 
          23 24 25 26 27 28 
        exit: 0
    tuesday 31:
      - run: ./calendar 3 31
        stdout: |
          SU MO TU WE TH FR SA
                 1  2  3  4  5 
           6  7  8  9 10 11 12 
          13 14 15 16 17 18 19 
          20 21 22 23 24 25 26 
          27 28 29 30 31 
        exit: 0
