check50:
  checks:
    east star 2:
      - run: ./wordlinks
        stdin:
          - east
          - star
        stdout: east star 2
        exit: 0
    spam pam 3:
      - run: ./wordlinks
        stdin:
          - spam
          - pam
        stdout: spam pam 3
        exit: 0
    a ant 1:
      - run: ./wordlinks
        stdin:
          - a
          - ant
        stdout: a ant 1
        exit: 0
    alpha a 1:
      - run: ./wordlinks
        stdin:
          - alpha
          - a
        stdout: alpha a 1
        exit: 0
    spike pike 4:
      - run: ./wordlinks
        stdin:
          - spike
          - pike
        stdout: spike pike 4
        exit: 0
    venus mars 0:
      - run: ./wordlinks
        stdin:
          - venus
          - mars
        stdout: venus mars 0
        exit: 0
    aabca abcad (Noah's test) 4:
      - run: ./wordlinks
        stdin:
          - aabca
          - abcad
        stdout: aabca abcad 4
        exit: 0
        